siteTitle = "Blog by John Carlo Arellano"
siteDescr = "Lorem Ipsum is simply dummy text of the printing and typesetting industry."
siteAuthor = "John Carlo Arellano"

siteTelegramUrl = "#"
siteTwitterUrl = "#"
siteGithubUrl = "#"
siteEmailUrl = "#"
siteRssUrl = "#"
siteVkUrl = "#"

googleAnalyticsId = ""

linkPrefix = "/gatsby-starter-lumen"
