siteTitle = "Blog by John Carlo Arellano"
siteDescr = "Web Developer"
siteAuthor = "John Carlo Arellano"

siteTelegramUrl = "https://telegram.me/jcfa01"
siteTwitterUrl = "https://twitter.com/jcfa01"
siteGithubUrl = "https://github.com/jcfa01"
siteEmailUrl = "jcfa01@gmail.com"
siteRssUrl = "#"
siteVkUrl = "#"

googleAnalyticsId = ""

linkPrefix = "/gatsby-starter-lumen"
